CREATE TABLE events(ID INT AUTO_INCREMENT, NAME VARCHAR(255), START_TIME  VARCHAR(255), VENUE VARCHAR(255), ORGANIZER_NAME VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE tickets(ID INT AUTO_INCREMENT, EVENT_ID INT, TOTAL INT, BOOKED INT, TICKET_TYPE VARCHAR(255), PRICE DECIMAL(6,2), PRIMARY KEY (ID));
